import Foundation
import SwiftUI
import UIKit

/// 「知识」主页：
/// - 提问：向 OpenClaw Agent 通用提问（HomeKnowledgeAskSupport，会话基底 key = knowledge）；
/// - 文件：入口进入网关工作区文件浏览器（agents.workspace.list/get RPC），文件内可基于内容提问。
@MainActor
struct HomeKnowledgeView: View {

    @Environment(NodeAppModel.self) private var appModel

    @State private var question = ""
    @State private var isAsking = false
    @State private var askPhaseText: String?
    @State private var answers: [HomeKnowledgeQA] = []
    @State private var errorMessage: String?
    @State private var noticeMessage: String?
    @FocusState private var questionFocused: Bool

    /// 快捷动作「提问」时预聚焦输入框。
    private let focusQuestionOnAppear: Bool

    init(focusQuestionOnAppear: Bool = false) {
        self.focusQuestionOnAppear = focusQuestionOnAppear
    }

    var body: some View {
        List {
            askSection
            filesSection
        }
        .listStyle(.insetGrouped)
        .navigationTitle(String(localized: "Knowledge"))
        .navigationBarTitleDisplayMode(.inline)
        .alert(
            Text(String(localized: "Notice")),
            isPresented: Binding(
                get: { noticeMessage != nil },
                set: { if !$0 { noticeMessage = nil } }
            )
        ) {
            Button(String(localized: "OK"), role: .cancel) { noticeMessage = nil }
        } message: {
            Text(noticeMessage ?? "")
        }
        .onAppear {
            if focusQuestionOnAppear {
                questionFocused = true
            }
        }
    }

    // MARK: - 提问区

    @ViewBuilder
    private var askSection: some View {
        Section {
            TextField(
                String(localized: "Ask about your files or anything else"),
                text: $question,
                axis: .vertical
            )
            .lineLimit(2...5)
            .font(OpenClawType.body)
            .focused($questionFocused)
            .disabled(isAsking)

            if let errorMessage {
                Text(errorMessage)
                    .font(OpenClawType.footnote)
                    .foregroundStyle(OpenClawBrand.warn)
            }

            Button {
                Task { await ask() }
            } label: {
                HStack(spacing: 8) {
                    if isAsking {
                        ProgressView()
                    }
                    Text(isAsking ? String(localized: "Asking…") : String(localized: "Ask"))
                        .font(OpenClawType.subheadMedium)
                }
                .frame(maxWidth: .infinity)
            }
            .buttonStyle(.borderedProminent)
            .tint(OpenClawBrand.accent)
            .disabled(isAsking || !canAsk)

            if isAsking, let askPhaseText {
                HStack(spacing: 8) {
                    ProgressView()
                        .controlSize(.small)
                    Text(askPhaseText)
                        .font(OpenClawType.caption)
                        .foregroundStyle(.secondary)
                }
            }

            if !answers.isEmpty {
                ForEach(answers) { qa in
                    qaRow(qa)
                }
            }
        } header: {
            Text(String(localized: "Ask the Agent"))
        } footer: {
            Text(String(localized: "Answers are generated by the OpenClaw agent; verify important details."))
        }
    }

    private var canAsk: Bool {
        !question.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    private func qaRow(_ qa: HomeKnowledgeQA) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack(alignment: .firstTextBaseline, spacing: 8) {
                Text(qa.question)
                    .font(OpenClawType.subheadMedium)
                    .foregroundStyle(.primary)
                Spacer(minLength: 8)
                Button {
                    UIPasteboard.general.string = qa.answer
                    noticeMessage = String(localized: "Copied to clipboard.")
                } label: {
                    Image(systemName: "doc.on.doc")
                }
                .buttonStyle(.borderless)
                .accessibilityLabel(String(localized: "Copy"))
            }
            if let sourcePath = qa.sourcePath, !sourcePath.isEmpty {
                Text(sourcePath)
                    .font(OpenClawType.caption2)
                    .foregroundStyle(.secondary)
                    .lineLimit(1)
            }
            HomeMarkdownText(markdown: qa.answer)
        }
        .padding(.vertical, 4)
    }

    // MARK: - 文件区

    @ViewBuilder
    private var filesSection: some View {
        Section {
            NavigationLink {
                HomeKnowledgeFileBrowserHost()
            } label: {
                Label(String(localized: "Workspace Files"), systemImage: "folder")
                    .font(OpenClawType.subhead)
            }
        } header: {
            Text(String(localized: "Gateway Files"))
        } footer: {
            Text(String(localized: "Files come from the connected OpenClaw agent's workspace via the gateway."))
        }
    }

    // MARK: - 动作

    private func ask() async {
        let trimmed = question.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        isAsking = true
        askPhaseText = String(localized: "Waiting for the agent…")
        errorMessage = nil
        defer {
            isAsking = false
            askPhaseText = nil
        }
        do {
            let answer = try await HomeKnowledgeAskSupport.ask(
                appModel: appModel,
                question: trimmed)
            answers.insert(HomeKnowledgeQA(question: trimmed, answer: answer), at: 0)
            question = ""
        } catch {
            errorMessage = error.localizedDescription
        }
    }
}

/// 文件浏览器宿主：从环境取当前 Agent，直接进入工作区文件浏览。
@MainActor
struct HomeKnowledgeFileBrowserHost: View {
    @Environment(NodeAppModel.self) private var appModel

    var body: some View {
        HomeKnowledgeFileBrowserView(agentId: appModel.chatAgentId)
    }
}

