//
//  LoveKeyboardPanelView.swift
//  Keyboard
//
//  AI love keyboard panel, ported from LoveKeyboard.
//  Four tabs: quick replies, icebreakers, personas and
//  love messages, generated by DeepSeek and inserted
//  inline or published to the candidate bar.
//

import SwiftUI

/// AI love keyboard panel with four tabs.
struct LoveKeyboardPanelView: View {

    let onClose: () -> Void
    let onPaste: () -> String?
    let onSelect: (String) -> Void
    let onPublish: ([String]) -> Void

    /// Panel tabs.
    enum Tab: String, CaseIterable, Identifiable {
        case quickReply = "一键回复"
        case icebreaker = "开场白"
        case persona = "人设"
        case loveWords = "情话"

        var id: String { rawValue }
    }

    @State private var selectedTab: Tab = .quickReply

    // Quick reply state.
    @State private var replyInput = ""
    @State private var selectedRoleId: String?
    @State private var selectedIntimacy: IntimacyLevel = .lover

    // Icebreaker state.
    @State private var selectedScene = IcebreakerScenes.all[0]

    // Persona state.
    @State private var selectedCategory: RoleCategory = .all

    // Love words state.
    @State private var loveInput = ""
    @State private var selectedStyle: ReplyStyle = .sweet

    @State private var results: [String] = []
    @State private var isLoading = false
    @State private var errorMessage: String?

    private var quickReplyRoles: [ChatRole] {
        PresetRoles.getRoles(by: .helpReply)
    }

    private var filteredRoles: [ChatRole] {
        PresetRoles.getRoles(by: selectedCategory)
    }

    private var selectedRole: ChatRole? {
        quickReplyRoles.first { $0.id == selectedRoleId } ?? quickReplyRoles.first
    }

    var body: some View {
        VStack(spacing: 10) {
            header
            tabBar

            ScrollView {
                VStack(spacing: 12) {
                    switch selectedTab {
                    case .quickReply: quickReplySection
                    case .icebreaker: icebreakerSection
                    case .persona: personaSection
                    case .loveWords: loveWordsSection
                    }

                    if selectedTab != .persona {
                        generateButton
                    }

                    if let errorMessage {
                        Text(errorMessage)
                            .font(.caption)
                            .foregroundStyle(.red)
                            .frame(maxWidth: .infinity, alignment: .leading)
                    }

                    resultList
                }
                .padding(.horizontal, 8)
                .padding(.bottom, 8)
            }
        }
        .padding(.top, 4)
        .background(Color(.systemBackground))
        .onAppear(perform: loadSavedRole)
    }

    // MARK: - Sections

    private var quickReplySection: some View {
        VStack(spacing: 10) {
            Text(replyInput.isEmpty
                ? LKString("粘贴或输入要回复的内容", "Paste or type the message to reply")
                : replyInput)
                .font(.subheadline)
                .foregroundStyle(replyInput.isEmpty ? .secondary : .primary)
                .lineLimit(3)
                .frame(maxWidth: .infinity, minHeight: 44, alignment: .topLeading)
                .padding(8)
                .background(Color(.secondarySystemBackground))
                .clipShape(RoundedRectangle(cornerRadius: 8))

            ScrollView(.horizontal, showsIndicators: false) {
                HStack(spacing: 6) {
                    ForEach(quickReplyRoles) { role in
                        chip(role.name, selected: selectedRoleId == role.id) {
                            selectedRoleId = role.id
                            StorageService.shared.currentRoleId = role.id
                            resetResults()
                        }
                    }
                }
            }

            intimacyPicker
        }
    }

    private var icebreakerSection: some View {
        VStack(spacing: 10) {
            ScrollView(.horizontal, showsIndicators: false) {
                HStack(spacing: 6) {
                    ForEach(IcebreakerScenes.all, id: \.self) { scene in
                        chip(scene, selected: selectedScene == scene) {
                            selectedScene = scene
                            resetResults()
                        }
                    }
                }
            }

            Text(LKString("选择场景后点击下方生成开场白", "Pick a scene and generate icebreakers below"))
                .font(.caption)
                .foregroundStyle(.secondary)
                .frame(maxWidth: .infinity, alignment: .leading)
        }
    }

    private var personaSection: some View {
        VStack(spacing: 8) {
            ScrollView(.horizontal, showsIndicators: false) {
                HStack(spacing: 6) {
                    ForEach(RoleCategory.allCases, id: \.self) { category in
                        chip(category.rawValue, selected: selectedCategory == category) {
                            selectedCategory = category
                            resetResults()
                        }
                    }
                }
            }

            ForEach(filteredRoles) { role in
                Button {
                    selectedRoleId = role.id
                    StorageService.shared.currentRoleId = role.id
                    resetResults()
                } label: {
                    HStack(spacing: 10) {
                        VStack(alignment: .leading, spacing: 2) {
                            Text(role.name)
                                .font(.body.weight(.medium))
                            Text(role.description)
                                .font(.caption)
                                .foregroundStyle(.secondary)
                                .lineLimit(1)
                        }
                        Spacer()
                        if selectedRoleId == role.id {
                            Image(systemName: "checkmark.circle.fill")
                                .foregroundStyle(Color.accentColor)
                        }
                    }
                    .padding(10)
                    .background(Color(.secondarySystemBackground))
                    .clipShape(RoundedRectangle(cornerRadius: 8))
                }
                .buttonStyle(.plain)
            }
        }
    }

    private var loveWordsSection: some View {
        VStack(spacing: 10) {
            Text(loveInput.isEmpty
                ? LKString("输入想表达的意思，如：今晚想你了", "Type what you want to say")
                : loveInput)
                .font(.subheadline)
                .foregroundStyle(loveInput.isEmpty ? .secondary : .primary)
                .lineLimit(3)
                .frame(maxWidth: .infinity, minHeight: 44, alignment: .topLeading)
                .padding(8)
                .background(Color(.secondarySystemBackground))
                .clipShape(RoundedRectangle(cornerRadius: 8))

            ScrollView(.horizontal, showsIndicators: false) {
                HStack(spacing: 6) {
                    ForEach(ReplyStyle.allCases, id: \.self) { style in
                        chip(style.rawValue, selected: selectedStyle == style) {
                            selectedStyle = style
                            resetResults()
                        }
                    }
                }
            }

            intimacyPicker
        }
    }

    private var intimacyPicker: some View {
        VStack(alignment: .leading, spacing: 6) {
            Text(LKString("亲密度", "Intimacy"))
                .font(.caption)
                .foregroundStyle(.secondary)
            HStack(spacing: 4) {
                ForEach(IntimacyLevel.allCases, id: \.self) { level in
                    Button {
                        selectedIntimacy = level
                        resetResults()
                    } label: {
                        Text(level.rawValue)
                            .font(.caption2)
                            .frame(maxWidth: .infinity)
                            .padding(.vertical, 6)
                            .background(selectedIntimacy == level ? Color.accentColor.opacity(0.2) : Color(.tertiarySystemBackground))
                            .clipShape(Capsule())
                    }
                    .buttonStyle(.plain)
                }
            }
        }
    }

    private var generateButton: some View {
        Button {
            generate()
        } label: {
            Group {
                if isLoading {
                    ProgressView()
                        .frame(height: 20)
                } else {
                    Text(generateButtonTitle)
                        .font(.body.bold())
                }
            }
            .frame(maxWidth: .infinity)
            .frame(height: 36)
            .background(canGenerate ? Color.accentColor.opacity(0.85) : Color(.tertiarySystemBackground))
            .foregroundStyle(canGenerate ? Color.white : .secondary)
            .clipShape(RoundedRectangle(cornerRadius: 8))
        }
        .buttonStyle(.plain)
        .disabled(!canGenerate)
    }

    private var generateButtonTitle: String {
        switch selectedTab {
        case .quickReply: return LKString("AI 生成回复", "Generate Replies")
        case .icebreaker: return LKString("AI 生成开场白", "Generate Icebreakers")
        case .persona: return LKString("生成", "Generate")
        case .loveWords: return LKString("AI 生成情话", "Generate Love Words")
        }
    }

    private var canGenerate: Bool {
        if isLoading { return false }
        switch selectedTab {
        case .quickReply: return !replyInput.isEmpty && selectedRole != nil
        case .icebreaker: return true
        case .persona: return false
        case .loveWords: return true
        }
    }

    @ViewBuilder
    private var resultList: some View {
        if !results.isEmpty {
            VStack(spacing: 6) {
                HStack {
                    Text(LKString("生成结果", "Results"))
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    Spacer()
                    Button {
                        onPublish(results)
                    } label: {
                        Text(LKString("显示到候选栏", "Show in candidate bar"))
                            .font(.caption)
                            .padding(.horizontal, 8)
                            .padding(.vertical, 4)
                            .background(Color.pink.opacity(0.12))
                            .clipShape(Capsule())
                    }
                    .buttonStyle(.plain)
                }
                ForEach(results, id: \.self) { reply in
                    Button {
                        onSelect(reply)
                        onClose()
                    } label: {
                        Text(reply)
                            .font(.body)
                            .frame(maxWidth: .infinity, alignment: .leading)
                            .padding(.horizontal, 10)
                            .padding(.vertical, 8)
                            .background(Color(.secondarySystemBackground))
                            .clipShape(RoundedRectangle(cornerRadius: 6))
                    }
                    .buttonStyle(.plain)
                }
            }
        }
    }

    // MARK: - Header & Tabs

    private var header: some View {
        HStack {
            Button {
                onClose()
            } label: {
                Text(verbatim: "×")
                    .font(.title)
                    .frame(width: 40, height: 40)
            }
            .buttonStyle(.plain)

            Spacer()

            Text(LKString("AI 恋爱键盘", "AI Love Keyboard"))
                .font(.headline)

            Spacer()

            Button {
                if let pasted = onPaste() {
                    applyPaste(pasted)
                }
            } label: {
                Text(LKString("粘贴", "Paste"))
                    .font(.body)
                    .frame(width: 48, height: 40)
            }
            .buttonStyle(.plain)
        }
        .padding(.horizontal, 8)
    }

    private var tabBar: some View {
        HStack(spacing: 4) {
            ForEach(Tab.allCases) { tab in
                Button {
                    selectedTab = tab
                    resetResults()
                } label: {
                    Text(tab.rawValue)
                        .font(.subheadline)
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, 7)
                        .background(selectedTab == tab ? Color.accentColor.opacity(0.2) : Color(.tertiarySystemBackground))
                        .clipShape(Capsule())
                }
                .buttonStyle(.plain)
            }
        }
        .padding(.horizontal, 8)
    }

    // MARK: - Helpers

    private func chip(_ title: String, selected: Bool, action: @escaping () -> Void) -> some View {
        Button(action: action) {
            Text(title)
                .font(.caption)
                .padding(.horizontal, 10)
                .padding(.vertical, 6)
                .background(selected ? Color.accentColor.opacity(0.2) : Color(.tertiarySystemBackground))
                .clipShape(Capsule())
                .overlay(Capsule().stroke(selected ? Color.accentColor : Color.clear, lineWidth: 1))
        }
        .buttonStyle(.plain)
    }

    private func applyPaste(_ text: String) {
        switch selectedTab {
        case .quickReply: replyInput = text
        case .icebreaker: break
        case .persona: break
        case .loveWords: loveInput = text
        }
        resetResults()
    }

    private func resetResults() {
        results = []
        errorMessage = nil
    }

    private func loadSavedRole() {
        guard selectedRoleId == nil else { return }
        if let saved = StorageService.shared.currentRoleId {
            selectedRoleId = saved
        }
    }

    private func generate() {
        guard selectedTab != .persona else { return }
        isLoading = true
        errorMessage = nil
        results = []
        Task {
            do {
                let generated: [String]
                switch selectedTab {
                case .quickReply:
                    guard let role = selectedRole, !replyInput.isEmpty else { return }
                    generated = try await APIService.shared.generateReply(
                        content: replyInput,
                        role: role,
                        intimacy: selectedIntimacy,
                        count: 5
                    )
                case .icebreaker:
                    generated = try await APIService.shared.generateIcebreaker(
                        scene: selectedScene,
                        count: 4
                    )
                case .persona:
                    generated = []
                case .loveWords:
                    generated = try await APIService.shared.generateLoveMessage(
                        content: loveInput.isEmpty
                            ? LKString("表达对 TA 的喜欢和想念", "Tell them you miss them")
                            : loveInput,
                        style: selectedStyle,
                        intimacy: selectedIntimacy,
                        count: 4
                    )
                }
                await MainActor.run {
                    results = generated
                    isLoading = false
                }
            } catch {
                await MainActor.run {
                    errorMessage = (error as? APIError)?.errorDescription ?? error.localizedDescription
                    isLoading = false
                }
            }
        }
    }
}

/// Preset icebreaker scenes.
enum IcebreakerScenes {
    static let all = [
        "刚加微信不知道怎么开口",
        "追求期拉近距离",
        "约会邀请",
        "道歉哄人",
        "早安晚安问候",
        "很久没联系想重新搭话",
        "纪念日/节日祝福"
    ]
}
