//
//  PinyinEngine.swift
//  Keyboard
//
//  Chinese pinyin input engine, ported from LoveKeyboard
//  (https://github.com/Hegui-lab/LoveKeyboard) with an
//  extended common-character dictionary.
//

import Foundation

/// Pinyin input engine - converts pinyin syllables to
/// Chinese character candidates.
class PinyinEngine {

    /// Pinyin to candidate characters mapping.
    private var pinyinDict: [String: [String]] = [:]

    /// Whether the dictionary is loaded.
    private var isLoaded = false

    // MARK: - Init

    init() {
        loadBasicDict()
    }

    // MARK: - Public API

    /// Returns candidate characters for a pinyin syllable.
    func getCandidates(for pinyin: String) -> [String] {
        guard !pinyin.isEmpty else { return [] }

        let lowercased = pinyin.lowercased()
        var results: [String] = []

        // Exact match
        if let exact = pinyinDict[lowercased] {
            results.append(contentsOf: exact)
        }

        // Prefix match
        for (key, values) in pinyinDict where key.hasPrefix(lowercased) && key != lowercased {
            results.append(contentsOf: values.prefix(3))
        }

        return Array(results.prefix(9))
    }

    // MARK: - Dictionary

    /// Loads the built-in pinyin dictionary.
    private func loadBasicDict() {
        // A
        pinyinDict["a"] = ["啊", "阿", "呵"]
        pinyinDict["ai"] = ["爱", "哎", "唉", "矮"]
        pinyinDict["an"] = ["安", "按", "暗", "岸"]
        pinyinDict["ang"] = ["昂", "肮"]
        pinyinDict["ao"] = ["奥", "傲", "熬"]
        // B
        pinyinDict["ba"] = ["吧", "把", "爸", "八"]
        pinyinDict["bai"] = ["白", "百", "拜", "败"]
        pinyinDict["ban"] = ["半", "办", "班", "般"]
        pinyinDict["bang"] = ["帮", "棒", "傍"]
        pinyinDict["bao"] = ["宝", "报", "包", "保"]
        pinyinDict["bei"] = ["被", "北", "背", "杯"]
        pinyinDict["ben"] = ["本", "奔", "笨"]
        pinyinDict["bi"] = ["比", "笔", "必", "闭"]
        pinyinDict["bian"] = ["变", "边", "便", "遍"]
        pinyinDict["biao"] = ["表", "标", "彪"]
        pinyinDict["bie"] = ["别", "憋"]
        pinyinDict["bin"] = ["宾", "彬"]
        pinyinDict["bing"] = ["病", "并", "冰", "饼"]
        pinyinDict["bo"] = ["波", "播", "博", "伯"]
        pinyinDict["bu"] = ["不", "步", "部", "布"]
        // C
        pinyinDict["ca"] = ["擦"]
        pinyinDict["cai"] = ["才", "菜", "猜", "彩"]
        pinyinDict["can"] = ["参", "残", "餐"]
        pinyinDict["cang"] = ["藏", "仓"]
        pinyinDict["cao"] = ["草", "操"]
        pinyinDict["ce"] = ["侧", "策", "测"]
        pinyinDict["ceng"] = ["层", "曾"]
        pinyinDict["cha"] = ["查", "茶", "差", "插"]
        pinyinDict["chai"] = ["拆", "柴"]
        pinyinDict["chan"] = ["产", "缠", "铲"]
        pinyinDict["chang"] = ["长", "常", "场", "厂"]
        pinyinDict["chao"] = ["超", "朝", "炒"]
        pinyinDict["che"] = ["车", "扯", "撤"]
        pinyinDict["chen"] = ["陈", "晨", "沉"]
        pinyinDict["cheng"] = ["成", "城", "程", "称"]
        pinyinDict["chi"] = ["吃", "迟", "池", "持"]
        pinyinDict["chong"] = ["重", "冲", "虫"]
        pinyinDict["chou"] = ["抽", "愁", "丑"]
        pinyinDict["chu"] = ["出", "初", "除", "处"]
        pinyinDict["chuan"] = ["穿", "船", "传"]
        pinyinDict["chuang"] = ["窗", "床", "创"]
        pinyinDict["chui"] = ["吹", "垂"]
        pinyinDict["chun"] = ["春", "纯", "唇"]
        pinyinDict["ci"] = ["次", "此", "词", "刺"]
        pinyinDict["cong"] = ["从", "聪", "葱"]
        pinyinDict["cu"] = ["粗", "促"]
        pinyinDict["cun"] = ["存", "村"]
        pinyinDict["cuo"] = ["错", "搓"]
        // D
        pinyinDict["da"] = ["大", "打", "达", "答"]
        pinyinDict["dai"] = ["带", "代", "待", "袋"]
        pinyinDict["dan"] = ["但", "蛋", "担", "单"]
        pinyinDict["dang"] = ["当", "档", "党"]
        pinyinDict["dao"] = ["到", "道", "倒", "刀"]
        pinyinDict["de"] = ["的", "得", "地", "德"]
        pinyinDict["deng"] = ["等", "灯", "邓"]
        pinyinDict["di"] = ["地", "第", "低", "底"]
        pinyinDict["dian"] = ["点", "电", "店", "典"]
        pinyinDict["diao"] = ["掉", "调", "钓"]
        pinyinDict["die"] = ["跌", "爹"]
        pinyinDict["ding"] = ["定", "顶", "订"]
        pinyinDict["dong"] = ["动", "东", "懂", "冬"]
        pinyinDict["dou"] = ["都", "斗", "豆"]
        pinyinDict["du"] = ["读", "度", "独", "毒"]
        pinyinDict["duan"] = ["短", "段", "断"]
        pinyinDict["dui"] = ["对", "队", "堆"]
        pinyinDict["dun"] = ["顿", "蹲"]
        pinyinDict["duo"] = ["多", "朵", "躲"]
        // E
        pinyinDict["e"] = ["饿", "额", "鹅"]
        pinyinDict["en"] = ["嗯", "恩"]
        pinyinDict["er"] = ["二", "耳", "而"]
        // F
        pinyinDict["fa"] = ["发", "法", "罚"]
        pinyinDict["fan"] = ["反", "饭", "烦", "翻"]
        pinyinDict["fang"] = ["方", "房", "放", "防"]
        pinyinDict["fei"] = ["非", "飞", "费", "肥"]
        pinyinDict["fen"] = ["分", "粉", "份", "芬"]
        pinyinDict["feng"] = ["风", "封", "疯", "峰"]
        pinyinDict["fu"] = ["服", "付", "福", "复"]
        // G
        pinyinDict["gai"] = ["该", "改", "盖"]
        pinyinDict["gan"] = ["感", "敢", "干", "赶"]
        pinyinDict["gang"] = ["刚", "港", "钢"]
        pinyinDict["gao"] = ["高", "告", "搞"]
        pinyinDict["ge"] = ["个", "哥", "歌", "各"]
        pinyinDict["gei"] = ["给"]
        pinyinDict["gen"] = ["跟", "根"]
        pinyinDict["geng"] = ["更", "耕"]
        pinyinDict["gong"] = ["工", "公", "共", "功"]
        pinyinDict["gou"] = ["够", "狗", "购"]
        pinyinDict["gu"] = ["故", "古", "顾", "鼓"]
        pinyinDict["gua"] = ["挂", "瓜"]
        pinyinDict["guai"] = ["怪", "乖"]
        pinyinDict["guan"] = ["关", "管", "观", "馆"]
        pinyinDict["guang"] = ["光", "广"]
        pinyinDict["gui"] = ["贵", "归", "鬼"]
        pinyinDict["gun"] = ["滚", "棍"]
        pinyinDict["guo"] = ["过", "国", "果"]
        // H
        pinyinDict["hai"] = ["还", "海", "害", "孩"]
        pinyinDict["han"] = ["喊", "汉", "汗", "寒"]
        pinyinDict["hang"] = ["行", "航", "杭"]
        pinyinDict["hao"] = ["好", "号", "毫"]
        pinyinDict["he"] = ["和", "喝", "河", "何"]
        pinyinDict["hei"] = ["黑"]
        pinyinDict["hen"] = ["很", "恨", "狠"]
        pinyinDict["heng"] = ["横", "哼"]
        pinyinDict["hong"] = ["红", "洪", "哄"]
        pinyinDict["hou"] = ["后", "候", "厚"]
        pinyinDict["hu"] = ["胡", "湖", "虎", "户"]
        pinyinDict["hua"] = ["话", "花", "画", "华"]
        pinyinDict["huai"] = ["坏", "怀"]
        pinyinDict["huan"] = ["换", "欢", "还", "环"]
        pinyinDict["huang"] = ["黄", "慌", "皇"]
        pinyinDict["hui"] = ["会", "回", "灰", "挥"]
        pinyinDict["hun"] = ["混", "婚", "魂"]
        pinyinDict["huo"] = ["活", "火", "或", "货"]
        // J
        pinyinDict["ji"] = ["几", "机", "鸡", "级"]
        pinyinDict["jia"] = ["家", "加", "假", "价"]
        pinyinDict["jian"] = ["见", "间", "件", "建"]
        pinyinDict["jiang"] = ["将", "讲", "江", "奖"]
        pinyinDict["jiao"] = ["叫", "教", "交", "角"]
        pinyinDict["jie"] = ["接", "姐", "解", "界"]
        pinyinDict["jin"] = ["进", "金", "今", "紧"]
        pinyinDict["jing"] = ["经", "静", "京", "精"]
        pinyinDict["jiu"] = ["就", "九", "酒", "旧"]
        pinyinDict["ju"] = ["句", "举", "局", "具"]
        pinyinDict["juan"] = ["卷", "捐"]
        pinyinDict["jue"] = ["觉", "决", "绝"]
        pinyinDict["jun"] = ["军", "君", "均"]
        // K
        pinyinDict["kai"] = ["开", "凯", "慨"]
        pinyinDict["kan"] = ["看", "砍"]
        pinyinDict["kang"] = ["抗", "康"]
        pinyinDict["kao"] = ["考", "靠", "烤"]
        pinyinDict["ke"] = ["可", "课", "客", "克"]
        pinyinDict["ken"] = ["肯", "啃"]
        pinyinDict["kong"] = ["空", "孔", "恐"]
        pinyinDict["kou"] = ["口", "扣"]
        pinyinDict["ku"] = ["哭", "苦", "库"]
        pinyinDict["kuai"] = ["快", "块", "筷"]
        pinyinDict["kuan"] = ["宽", "款"]
        pinyinDict["kuang"] = ["况", "狂"]
        pinyinDict["kun"] = ["困", "昆"]
        pinyinDict["kuo"] = ["阔", "扩"]
        // L
        pinyinDict["la"] = ["拉", "啦", "辣"]
        pinyinDict["lai"] = ["来", "赖", "莱"]
        pinyinDict["lan"] = ["蓝", "懒", "烂"]
        pinyinDict["lang"] = ["浪", "狼"]
        pinyinDict["lao"] = ["老", "劳", "牢"]
        pinyinDict["le"] = ["了", "乐"]
        pinyinDict["lei"] = ["累", "泪", "类"]
        pinyinDict["leng"] = ["冷", "愣"]
        pinyinDict["li"] = ["里", "力", "离", "理"]
        pinyinDict["lian"] = ["连", "脸", "练", "联"]
        pinyinDict["liang"] = ["两", "亮", "凉", "量"]
        pinyinDict["liao"] = ["了", "聊", "料"]
        pinyinDict["lie"] = ["列", "烈", "裂"]
        pinyinDict["lin"] = ["林", "临", "淋"]
        pinyinDict["ling"] = ["零", "领", "灵", "另"]
        pinyinDict["liu"] = ["六", "流", "留", "刘"]
        pinyinDict["long"] = ["龙", "隆", "弄"]
        pinyinDict["lou"] = ["楼", "漏"]
        pinyinDict["lu"] = ["路", "录", "陆", "露"]
        pinyinDict["luan"] = ["乱", "卵"]
        pinyinDict["lun"] = ["论", "轮"]
        pinyinDict["luo"] = ["落", "罗", "络"]
        // M
        pinyinDict["ma"] = ["吗", "妈", "马", "嘛"]
        pinyinDict["mai"] = ["买", "卖", "麦"]
        pinyinDict["man"] = ["慢", "满", "蛮"]
        pinyinDict["mang"] = ["忙", "盲"]
        pinyinDict["mao"] = ["毛", "猫", "冒"]
        pinyinDict["me"] = ["么", "嘛"]
        pinyinDict["mei"] = ["没", "美", "妹", "每"]
        pinyinDict["men"] = ["们", "门", "闷"]
        pinyinDict["meng"] = ["梦", "蒙", "猛"]
        pinyinDict["mi"] = ["米", "密", "迷", "秘"]
        pinyinDict["mian"] = ["面", "免", "棉"]
        pinyinDict["miao"] = ["秒", "妙", "庙"]
        pinyinDict["mie"] = ["灭"]
        pinyinDict["ming"] = ["名", "明", "命"]
        pinyinDict["miu"] = ["谬"]
        pinyinDict["mo"] = ["没", "摸", "莫", "默"]
        pinyinDict["mou"] = ["某", "谋"]
        pinyinDict["mu"] = ["目", "母", "木", "幕"]
        // N
        pinyinDict["na"] = ["那", "拿", "哪", "纳"]
        pinyinDict["nai"] = ["奶", "耐", "奈"]
        pinyinDict["nan"] = ["难", "南", "男"]
        pinyinDict["nang"] = ["囊"]
        pinyinDict["nao"] = ["闹", "脑"]
        pinyinDict["ne"] = ["呢", "哪"]
        pinyinDict["nei"] = ["内", "那"]
        pinyinDict["nen"] = ["嫩"]
        pinyinDict["neng"] = ["能"]
        pinyinDict["ni"] = ["你", "呢", "泥", "尼"]
        pinyinDict["nian"] = ["年", "念", "粘"]
        pinyinDict["niang"] = ["娘"]
        pinyinDict["niao"] = ["鸟", "尿"]
        pinyinDict["nie"] = ["捏", "聂"]
        pinyinDict["nin"] = ["您"]
        pinyinDict["ning"] = ["宁", "拧"]
        pinyinDict["niu"] = ["牛", "扭"]
        pinyinDict["nong"] = ["弄", "农", "浓"]
        pinyinDict["nu"] = ["怒", "努"]
        pinyinDict["nuan"] = ["暖"]
        pinyinDict["nuo"] = ["诺", "挪"]
        // O
        pinyinDict["ou"] = ["偶", "欧", "呕"]
        // P
        pinyinDict["pa"] = ["怕", "爬", "帕"]
        pinyinDict["pai"] = ["派", "排", "牌"]
        pinyinDict["pan"] = ["盘", "判", "盼"]
        pinyinDict["pang"] = ["旁", "胖"]
        pinyinDict["pao"] = ["跑", "抛", "炮"]
        pinyinDict["pei"] = ["陪", "配", "赔"]
        pinyinDict["pen"] = ["喷", "盆"]
        pinyinDict["peng"] = ["朋", "碰", "捧"]
        pinyinDict["pi"] = ["批", "皮", "屁", "疲"]
        pinyinDict["pian"] = ["片", "偏", "骗"]
        pinyinDict["piao"] = ["票", "漂", "飘"]
        pinyinDict["pin"] = ["品", "拼", "贫"]
        pinyinDict["ping"] = ["平", "瓶", "评", "凭"]
        pinyinDict["po"] = ["破", "婆", "坡"]
        pinyinDict["pu"] = ["普", "扑", "谱"]
        // Q
        pinyinDict["qi"] = ["起", "七", "气", "期"]
        pinyinDict["qia"] = ["恰", "掐"]
        pinyinDict["qian"] = ["前", "钱", "千", "签"]
        pinyinDict["qiang"] = ["强", "枪", "墙"]
        pinyinDict["qiao"] = ["巧", "桥", "敲"]
        pinyinDict["qie"] = ["切", "且", "窃"]
        pinyinDict["qin"] = ["亲", "琴", "勤"]
        pinyinDict["qing"] = ["请", "情", "清", "轻"]
        pinyinDict["qiong"] = ["穷"]
        pinyinDict["qiu"] = ["求", "球", "秋"]
        pinyinDict["qu"] = ["去", "取", "曲", "趣"]
        pinyinDict["quan"] = ["全", "圈", "权", "劝"]
        pinyinDict["que"] = ["却", "确", "缺"]
        pinyinDict["qun"] = ["群", "裙"]
        // R
        pinyinDict["ran"] = ["然", "染"]
        pinyinDict["rang"] = ["让", "嚷"]
        pinyinDict["rao"] = ["绕", "扰"]
        pinyinDict["re"] = ["热", "惹"]
        pinyinDict["ren"] = ["人", "认", "任", "忍"]
        pinyinDict["reng"] = ["仍", "扔"]
        pinyinDict["ri"] = ["日"]
        pinyinDict["rong"] = ["容", "荣", "融"]
        pinyinDict["rou"] = ["肉", "柔"]
        pinyinDict["ru"] = ["如", "入", "乳"]
        pinyinDict["ruan"] = ["软"]
        pinyinDict["rui"] = ["瑞", "锐"]
        pinyinDict["run"] = ["润"]
        pinyinDict["ruo"] = ["若", "弱"]
        // S
        pinyinDict["sa"] = ["撒", "萨"]
        pinyinDict["sai"] = ["赛", "塞"]
        pinyinDict["san"] = ["三", "散", "伞"]
        pinyinDict["sang"] = ["丧", "桑"]
        pinyinDict["sao"] = ["扫", "嫂"]
        pinyinDict["se"] = ["色", "涩"]
        pinyinDict["sen"] = ["森"]
        pinyinDict["seng"] = ["僧"]
        pinyinDict["sha"] = ["啥", "沙", "杀"]
        pinyinDict["shai"] = ["晒", "筛"]
        pinyinDict["shan"] = ["山", "闪", "善", "删"]
        pinyinDict["shang"] = ["上", "商", "伤", "尚"]
        pinyinDict["shao"] = ["少", "烧", "绍"]
        pinyinDict["she"] = ["社", "设", "射", "舍"]
        pinyinDict["shen"] = ["什", "身", "深", "神"]
        pinyinDict["sheng"] = ["生", "声", "省", "胜"]
        pinyinDict["shi"] = ["是", "时", "事", "十"]
        pinyinDict["shou"] = ["手", "收", "首", "受"]
        pinyinDict["shu"] = ["书", "数", "输", "熟"]
        pinyinDict["shua"] = ["刷"]
        pinyinDict["shuai"] = ["帅", "摔"]
        pinyinDict["shuan"] = ["拴"]
        pinyinDict["shuang"] = ["双", "爽"]
        pinyinDict["shui"] = ["水", "睡", "谁"]
        pinyinDict["shun"] = ["顺", "瞬"]
        pinyinDict["shuo"] = ["说", "硕"]
        pinyinDict["si"] = ["四", "死", "思", "私"]
        pinyinDict["song"] = ["送", "松", "宋"]
        pinyinDict["sou"] = ["搜", "艘"]
        pinyinDict["su"] = ["诉", "素", "速", "苏"]
        pinyinDict["suan"] = ["算", "酸"]
        pinyinDict["sui"] = ["岁", "随", "碎"]
        pinyinDict["sun"] = ["孙", "损"]
        pinyinDict["suo"] = ["所", "锁", "索"]
        // T
        pinyinDict["ta"] = ["他", "她", "它", "塔"]
        pinyinDict["tai"] = ["太", "台", "态", "抬"]
        pinyinDict["tan"] = ["谈", "叹", "摊", "探"]
        pinyinDict["tang"] = ["糖", "躺", "汤"]
        pinyinDict["tao"] = ["套", "逃", "桃", "讨"]
        pinyinDict["te"] = ["特"]
        pinyinDict["teng"] = ["疼", "腾"]
        pinyinDict["ti"] = ["题", "提", "体", "踢"]
        pinyinDict["tian"] = ["天", "田", "填", "甜"]
        pinyinDict["tiao"] = ["条", "跳", "挑"]
        pinyinDict["tie"] = ["铁", "贴"]
        pinyinDict["ting"] = ["听", "停", "挺", "厅"]
        pinyinDict["tong"] = ["同", "通", "痛", "统"]
        pinyinDict["tou"] = ["头", "偷", "透"]
        pinyinDict["tu"] = ["图", "土", "突", "途"]
        pinyinDict["tuan"] = ["团"]
        pinyinDict["tui"] = ["推", "退", "腿"]
        pinyinDict["tun"] = ["吞", "屯"]
        pinyinDict["tuo"] = ["脱", "托", "拖"]
        // W
        pinyinDict["wa"] = ["哇", "挖", "娃"]
        pinyinDict["wai"] = ["外", "歪"]
        pinyinDict["wan"] = ["完", "晚", "万", "玩"]
        pinyinDict["wang"] = ["王", "望", "忘", "网"]
        pinyinDict["wei"] = ["为", "位", "未", "围"]
        pinyinDict["wen"] = ["问", "文", "温", "闻"]
        pinyinDict["weng"] = ["翁"]
        pinyinDict["wo"] = ["我", "握", "窝"]
        pinyinDict["wu"] = ["无", "五", "物", "误"]
        // X
        pinyinDict["xi"] = ["系", "西", "希", "喜"]
        pinyinDict["xia"] = ["下", "夏", "吓"]
        pinyinDict["xian"] = ["先", "现", "线", "显"]
        pinyinDict["xiang"] = ["想", "向", "像", "相"]
        pinyinDict["xiao"] = ["小", "笑", "消", "校"]
        pinyinDict["xie"] = ["写", "谢", "些", "鞋"]
        pinyinDict["xin"] = ["新", "心", "信", "辛"]
        pinyinDict["xing"] = ["行", "星", "性", "兴"]
        pinyinDict["xiong"] = ["兄", "熊", "胸"]
        pinyinDict["xiu"] = ["休", "修", "秀"]
        pinyinDict["xu"] = ["需", "许", "续", "虚"]
        pinyinDict["xuan"] = ["选", "宣", "悬"]
        pinyinDict["xue"] = ["学", "雪", "血"]
        pinyinDict["xun"] = ["寻", "询", "训"]
        // Y
        pinyinDict["ya"] = ["呀", "压", "牙", "雅"]
        pinyinDict["yan"] = ["眼", "言", "颜", "演"]
        pinyinDict["yang"] = ["样", "养", "阳", "杨"]
        pinyinDict["yao"] = ["要", "药", "摇", "咬"]
        pinyinDict["ye"] = ["也", "夜", "业", "叶"]
        pinyinDict["yi"] = ["一", "以", "已", "意"]
        pinyinDict["yin"] = ["因", "音", "银", "印"]
        pinyinDict["ying"] = ["应", "影", "英", "硬"]
        pinyinDict["yo"] = ["哟"]
        pinyinDict["yong"] = ["用", "永", "勇", "拥"]
        pinyinDict["you"] = ["有", "又", "由", "友"]
        pinyinDict["yu"] = ["与", "于", "语", "雨"]
        pinyinDict["yuan"] = ["远", "园", "愿", "原"]
        pinyinDict["yue"] = ["月", "越", "约", "乐"]
        pinyinDict["yun"] = ["云", "运", "允"]
        // Z
        pinyinDict["za"] = ["咋", "杂"]
        pinyinDict["zai"] = ["在", "再", "载", "灾"]
        pinyinDict["zan"] = ["咱", "赞"]
        pinyinDict["zang"] = ["脏"]
        pinyinDict["zao"] = ["早", "造", "遭", "澡"]
        pinyinDict["ze"] = ["则", "责", "择"]
        pinyinDict["zei"] = ["贼"]
        pinyinDict["zen"] = ["怎"]
        pinyinDict["zeng"] = ["增", "曾"]
        pinyinDict["zha"] = ["炸", "扎", "渣"]
        pinyinDict["zhai"] = ["摘", "窄", "债"]
        pinyinDict["zhan"] = ["站", "战", "占", "展"]
        pinyinDict["zhang"] = ["长", "张", "章", "涨"]
        pinyinDict["zhao"] = ["找", "赵", "照", "招"]
        pinyinDict["zhe"] = ["这", "着", "者", "折"]
        pinyinDict["zhen"] = ["真", "阵", "镇", "针"]
        pinyinDict["zheng"] = ["正", "证", "争", "整"]
        pinyinDict["zhi"] = ["只", "之", "知", "直"]
        pinyinDict["zhong"] = ["中", "种", "重", "钟"]
        pinyinDict["zhou"] = ["周", "州", "皱"]
        pinyinDict["zhu"] = ["住", "主", "注", "祝"]
        pinyinDict["zhua"] = ["抓"]
        pinyinDict["zhuai"] = ["拽"]
        pinyinDict["zhuan"] = ["转", "专", "赚"]
        pinyinDict["zhuang"] = ["装", "壮", "撞"]
        pinyinDict["zhui"] = ["追", "坠"]
        pinyinDict["zhun"] = ["准"]
        pinyinDict["zhuo"] = ["桌", "捉", "着"]
        pinyinDict["zi"] = ["自", "子", "字", "资"]
        pinyinDict["zong"] = ["总", "宗", "纵"]
        pinyinDict["zou"] = ["走", "揍"]
        pinyinDict["zu"] = ["组", "足", "族", "租"]
        pinyinDict["zuan"] = ["钻"]
        pinyinDict["zui"] = ["最", "嘴", "罪"]
        pinyinDict["zun"] = ["尊", "遵"]
        pinyinDict["zuo"] = ["做", "作", "坐", "左"]

        isLoaded = true
    }
}
